---
- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    #when: ansible_distribution == "Ubuntu"
    #when: ansible_distribution in ["Debian","Ubuntu"]
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.2"

  - name: intall apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

